# Change these first
owner: rhpcs-mcmaster
repo: downtime

sites:
  - name: MACENGAGED
    url: https://www.macengaged.com/
  - name: eMuseum
    url: https://emuseum.mcmaster.ca/
  - name: MMOS
    url: https://museum.mcmaster.ca
  - name: Hacker News
    url: https://news.ycombinator.com
  

status-website:
  baseUrl: /downtime
  logoUrl: https://research.mcmaster.ca/app/themes/macsites-theme/img/logo.svg
  name: Upptime
  introTitle: "Open-source uptime monitor and status page"
  introMessage: **Real-time** data from our [GitHub repository](https://github.com/rhpcs-mcmaster/downtime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


