# Change these first
owner: rhpcs-mcmaster
repo: downtime

sites:
  - name: MACENGAGED
    url: https://www.macengaged.com/
  - name: eMuseum
    url: https://emuseum.mcmaster.ca/
  - name: MMOS
    url: https://museum.mcmaster.ca
  - name: arieal.mcmaster.ca
    url: https://arieal.mcmaster.ca
  - name: Back2Play
    url: https://b2p.mcmaster.ca/api/surveys
  - name: ms.math.mcmaster.ca
    url: http://ms.math.mcmaster.ca/uptimerobot
  - name: rhpcs.mcmaster.ca
    url: http://rhpcs.mcmaster.ca
  - name: web.mcmaster.ca
    url: http://web.mcmaster.ca/.well-known
  - name: Expected to always Fail
    url: http://rhpcssss.mmcmaster.ca
  

status-website:
  baseUrl: /downtime
  logoUrl: https://research.mcmaster.ca/app/themes/macsites-theme/img/logo.svg
  name: Upptime
  introTitle: "Uptime monitor and Status page"
  introMessage: "**Real-time** data from our [GitHub repository](https://github.com/rhpcs-mcmaster/downtime)." 
  navbar:
    - title: Status
      href: #
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


